version: '2'
services:
  suricata:
    container_name: suricata
    build: suricata
    image: soelk/suricata
    hostname: suricata
    volumes:
      - ./log/suricata:/var/log/suricata
    network_mode: "host"
    command: suricata -c /etc/suricata/suricata.yaml -i eth0
  elasticsearch:
    container_name: elasticsearch
    build: elasticsearch
    image: soelk/elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch -Des.network.host=0.0.0.0
    #command: /bin/bash
  kibana:
    container_name: kibana
    build: kibana
    image: soelk/kibana
    hostname: kibana
    ports:
      - "5601:5601"
    command: kibana
    links:
      - elasticsearch
  logstash:
    container_name: logstash
    build: logstash
    image: soelk/logstash
    hostname: logstash
    command: logstash -f /etc/logstash/conf.d
    #command: /bin/bash
    volumes:
      - ./logstash/conf:/etc/logstash/conf.d
      - ./log/suricata:/var/log/suricata
    ports:
      - "5000:5000"
    links:
      - elasticsearch

    
