version: '2'
services:
  suricata:
    container_name: suricata
    build: suricata
    image: soelk/suricata
    hostname: suricata
    volumes:
      - ./logs/suricata:/var/log/suricata
    network_mode: "host"
    # command: suricata -c /etc/suricata/suricata.yaml -i wlp5s0
    command: suricata -c /etc/suricata/suricata.yaml -i enp2s0
  elasticsearch:
    container_name: elasticsearch
    build: elasticsearch
    image: soelk/elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs/
      - ./data/es1:/usr/share/elasticsearch/data/
  #   #command: /bin/bash
  # kafka:
  #   container_name: kafka
  #   build: kafka
  #   image: soelk/kafka
  #   hostname: kafka
  #   #command: /bin/bash
  #   command: /bin/bash -c '/etc/init.d/zookeeper start && /data/kafka/bin/kafka-server-start.sh /data/kafka/config/server.properties'
  #   ports:
  #     - "2181:2181"
  #     - "9092:9092"
  # spark:
  #   container_name: spark
  #   build: spark
  #   image: soelk/spark
  #   hostname: spark
  #   command: /bin/bash
  #   ports:
  #     - "9999:9999"
  #   volumes:
  #     - ./spark/workdir:/workdir
  #   links:
  #     - kafka
  #     - elasticsearch
  kibana:
    container_name: kibana
    build: kibana
    image: soelk/kibana
    hostname: kibana
    ports:
      - "5601:5601"
    entrypoint: /wait-for-es.sh elasticsearch
    volumes:
      - ./logs/kibana:/var/log/kibana/
    links:
      - elasticsearch
  logstash:
    container_name: logstash
    build: logstash
    image: soelk/logstash
    hostname: logstash
    volumes:
      - ./logstash/conf:/etc/logstash/conf.d
      - ./logs/suricata:/var/log/suricata
      - ./logs/logstash:/var/log/logstash/
    ports:
      - "5000:5000"
    entrypoint: /wait-for-es.sh elasticsearch
    links:
    #  - kafka
      - elasticsearch
  evebox:
    container_name: evebox
    build: evebox
    image: soelk/evebox
    hostname: evebox
    ports:
      - "5636:5636"
    command: evebox -e http://elasticsearch:9200
    links:
      - elasticsearch
  nginx:
    container_name: nginx
    build: nginx
    image: soelk/nginx
    hostname: nginx
    #command: /bin/bash
    entrypoint: /wait-for-es.sh evebox kibana
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx/soelk/
    ports:
      - "80:80"
    links:
      - kibana
      - evebox
